#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonAppliWeb.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bddPandami")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertservicePref(servicePref instance);
    partial void UpdateservicePref(servicePref instance);
    partial void DeleteservicePref(servicePref instance);
    partial void InsertserviceName(serviceName instance);
    partial void UpdateserviceName(serviceName instance);
    partial void DeleteserviceName(serviceName instance);
    partial void Insertmember(member instance);
    partial void Updatemember(member instance);
    partial void Deletemember(member instance);
    partial void InsertdailyPref(dailyPref instance);
    partial void UpdatedailyPref(dailyPref instance);
    partial void DeletedailyPref(dailyPref instance);
    partial void Insertdays(days instance);
    partial void Updatedays(days instance);
    partial void Deletedays(days instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bddPandamiConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<servicePref> servicePref
		{
			get
			{
				return this.GetTable<servicePref>();
			}
		}
		
		public System.Data.Linq.Table<serviceName> serviceName
		{
			get
			{
				return this.GetTable<serviceName>();
			}
		}
		
		public System.Data.Linq.Table<member> member
		{
			get
			{
				return this.GetTable<member>();
			}
		}
		
		public System.Data.Linq.Table<dailyPref> dailyPref
		{
			get
			{
				return this.GetTable<dailyPref>();
			}
		}
		
		public System.Data.Linq.Table<days> days
		{
			get
			{
				return this.GetTable<days>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.servicePref")]
	public partial class servicePref : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _servicePrefID;
		
		private System.DateTime _choiceStartDate;
		
		private System.Nullable<System.DateTime> _choiceEndDate;
		
		private int _serviceNameFK;
		
		private EntitySet<member> _member;
		
		private EntityRef<serviceName> _serviceName;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnservicePrefIDChanging(int value);
    partial void OnservicePrefIDChanged();
    partial void OnchoiceStartDateChanging(System.DateTime value);
    partial void OnchoiceStartDateChanged();
    partial void OnchoiceEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnchoiceEndDateChanged();
    partial void OnserviceNameFKChanging(int value);
    partial void OnserviceNameFKChanged();
    #endregion
		
		public servicePref()
		{
			this._member = new EntitySet<member>(new Action<member>(this.attach_member), new Action<member>(this.detach_member));
			this._serviceName = default(EntityRef<serviceName>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servicePrefID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int servicePrefID
		{
			get
			{
				return this._servicePrefID;
			}
			set
			{
				if ((this._servicePrefID != value))
				{
					this.OnservicePrefIDChanging(value);
					this.SendPropertyChanging();
					this._servicePrefID = value;
					this.SendPropertyChanged("servicePrefID");
					this.OnservicePrefIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_choiceStartDate", DbType="DateTime2 NOT NULL")]
		public System.DateTime choiceStartDate
		{
			get
			{
				return this._choiceStartDate;
			}
			set
			{
				if ((this._choiceStartDate != value))
				{
					this.OnchoiceStartDateChanging(value);
					this.SendPropertyChanging();
					this._choiceStartDate = value;
					this.SendPropertyChanged("choiceStartDate");
					this.OnchoiceStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_choiceEndDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> choiceEndDate
		{
			get
			{
				return this._choiceEndDate;
			}
			set
			{
				if ((this._choiceEndDate != value))
				{
					this.OnchoiceEndDateChanging(value);
					this.SendPropertyChanging();
					this._choiceEndDate = value;
					this.SendPropertyChanged("choiceEndDate");
					this.OnchoiceEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serviceNameFK", DbType="Int NOT NULL")]
		public int serviceNameFK
		{
			get
			{
				return this._serviceNameFK;
			}
			set
			{
				if ((this._serviceNameFK != value))
				{
					if (this._serviceName.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnserviceNameFKChanging(value);
					this.SendPropertyChanging();
					this._serviceNameFK = value;
					this.SendPropertyChanged("serviceNameFK");
					this.OnserviceNameFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="servicePref_member", Storage="_member", ThisKey="servicePrefID", OtherKey="servicePrefFK")]
		public EntitySet<member> member
		{
			get
			{
				return this._member;
			}
			set
			{
				this._member.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="serviceName_servicePref", Storage="_serviceName", ThisKey="serviceNameFK", OtherKey="serviceID", IsForeignKey=true)]
		public serviceName serviceName
		{
			get
			{
				return this._serviceName.Entity;
			}
			set
			{
				serviceName previousValue = this._serviceName.Entity;
				if (((previousValue != value) 
							|| (this._serviceName.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._serviceName.Entity = null;
						previousValue.servicePref.Remove(this);
					}
					this._serviceName.Entity = value;
					if ((value != null))
					{
						value.servicePref.Add(this);
						this._serviceNameFK = value.serviceID;
					}
					else
					{
						this._serviceNameFK = default(int);
					}
					this.SendPropertyChanged("serviceName");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_member(member entity)
		{
			this.SendPropertyChanging();
			entity.servicePref = this;
		}
		
		private void detach_member(member entity)
		{
			this.SendPropertyChanging();
			entity.servicePref = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.serviceName")]
	public partial class serviceName : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _serviceID;
		
		private string _serviceName1;
		
		private int _serviceCategoryFK;
		
		private EntitySet<servicePref> _servicePref;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnserviceIDChanging(int value);
    partial void OnserviceIDChanged();
    partial void OnserviceName1Changing(string value);
    partial void OnserviceName1Changed();
    partial void OnserviceCategoryFKChanging(int value);
    partial void OnserviceCategoryFKChanged();
    #endregion
		
		public serviceName()
		{
			this._servicePref = new EntitySet<servicePref>(new Action<servicePref>(this.attach_servicePref), new Action<servicePref>(this.detach_servicePref));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serviceID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int serviceID
		{
			get
			{
				return this._serviceID;
			}
			set
			{
				if ((this._serviceID != value))
				{
					this.OnserviceIDChanging(value);
					this.SendPropertyChanging();
					this._serviceID = value;
					this.SendPropertyChanged("serviceID");
					this.OnserviceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="serviceName", Storage="_serviceName1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string serviceName1
		{
			get
			{
				return this._serviceName1;
			}
			set
			{
				if ((this._serviceName1 != value))
				{
					this.OnserviceName1Changing(value);
					this.SendPropertyChanging();
					this._serviceName1 = value;
					this.SendPropertyChanged("serviceName1");
					this.OnserviceName1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serviceCategoryFK", DbType="Int NOT NULL")]
		public int serviceCategoryFK
		{
			get
			{
				return this._serviceCategoryFK;
			}
			set
			{
				if ((this._serviceCategoryFK != value))
				{
					this.OnserviceCategoryFKChanging(value);
					this.SendPropertyChanging();
					this._serviceCategoryFK = value;
					this.SendPropertyChanged("serviceCategoryFK");
					this.OnserviceCategoryFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="serviceName_servicePref", Storage="_servicePref", ThisKey="serviceID", OtherKey="serviceNameFK")]
		public EntitySet<servicePref> servicePref
		{
			get
			{
				return this._servicePref;
			}
			set
			{
				this._servicePref.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_servicePref(servicePref entity)
		{
			this.SendPropertyChanging();
			entity.serviceName = this;
		}
		
		private void detach_servicePref(servicePref entity)
		{
			this.SendPropertyChanging();
			entity.serviceName = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.member")]
	public partial class member : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _memberID;
		
		private string _firstName;
		
		private string _lastName;
		
		private System.DateTime _birthdate;
		
		private string _email;
		
		private int _phone;
		
		private string _address;
		
		private string _login;
		
		private int _cityFK;
		
		private string _password;
		
		private System.Nullable<int> _serviceRequestFK;
		
		private System.Nullable<int> _dailyPrefFK;
		
		private System.Nullable<int> _servicePrefFK;
		
		private EntityRef<servicePref> _servicePref;
		
		private EntityRef<dailyPref> _dailyPref;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmemberIDChanging(int value);
    partial void OnmemberIDChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnbirthdateChanging(System.DateTime value);
    partial void OnbirthdateChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(int value);
    partial void OnphoneChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OncityFKChanging(int value);
    partial void OncityFKChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnserviceRequestFKChanging(System.Nullable<int> value);
    partial void OnserviceRequestFKChanged();
    partial void OndailyPrefFKChanging(System.Nullable<int> value);
    partial void OndailyPrefFKChanged();
    partial void OnservicePrefFKChanging(System.Nullable<int> value);
    partial void OnservicePrefFKChanged();
    #endregion
		
		public member()
		{
			this._servicePref = default(EntityRef<servicePref>);
			this._dailyPref = default(EntityRef<dailyPref>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memberID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int memberID
		{
			get
			{
				return this._memberID;
			}
			set
			{
				if ((this._memberID != value))
				{
					this.OnmemberIDChanging(value);
					this.SendPropertyChanging();
					this._memberID = value;
					this.SendPropertyChanged("memberID");
					this.OnmemberIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this.OnfirstNameChanging(value);
					this.SendPropertyChanging();
					this._firstName = value;
					this.SendPropertyChanged("firstName");
					this.OnfirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if ((this._lastName != value))
				{
					this.OnlastNameChanging(value);
					this.SendPropertyChanging();
					this._lastName = value;
					this.SendPropertyChanged("lastName");
					this.OnlastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthdate", DbType="DateTime2 NOT NULL")]
		public System.DateTime birthdate
		{
			get
			{
				return this._birthdate;
			}
			set
			{
				if ((this._birthdate != value))
				{
					this.OnbirthdateChanging(value);
					this.SendPropertyChanging();
					this._birthdate = value;
					this.SendPropertyChanged("birthdate");
					this.OnbirthdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="Int NOT NULL")]
		public int phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cityFK", DbType="Int NOT NULL")]
		public int cityFK
		{
			get
			{
				return this._cityFK;
			}
			set
			{
				if ((this._cityFK != value))
				{
					this.OncityFKChanging(value);
					this.SendPropertyChanging();
					this._cityFK = value;
					this.SendPropertyChanged("cityFK");
					this.OncityFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serviceRequestFK", DbType="Int")]
		public System.Nullable<int> serviceRequestFK
		{
			get
			{
				return this._serviceRequestFK;
			}
			set
			{
				if ((this._serviceRequestFK != value))
				{
					this.OnserviceRequestFKChanging(value);
					this.SendPropertyChanging();
					this._serviceRequestFK = value;
					this.SendPropertyChanged("serviceRequestFK");
					this.OnserviceRequestFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dailyPrefFK", DbType="Int")]
		public System.Nullable<int> dailyPrefFK
		{
			get
			{
				return this._dailyPrefFK;
			}
			set
			{
				if ((this._dailyPrefFK != value))
				{
					if (this._dailyPref.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndailyPrefFKChanging(value);
					this.SendPropertyChanging();
					this._dailyPrefFK = value;
					this.SendPropertyChanged("dailyPrefFK");
					this.OndailyPrefFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servicePrefFK", DbType="Int")]
		public System.Nullable<int> servicePrefFK
		{
			get
			{
				return this._servicePrefFK;
			}
			set
			{
				if ((this._servicePrefFK != value))
				{
					if (this._servicePref.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnservicePrefFKChanging(value);
					this.SendPropertyChanging();
					this._servicePrefFK = value;
					this.SendPropertyChanged("servicePrefFK");
					this.OnservicePrefFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="servicePref_member", Storage="_servicePref", ThisKey="servicePrefFK", OtherKey="servicePrefID", IsForeignKey=true)]
		public servicePref servicePref
		{
			get
			{
				return this._servicePref.Entity;
			}
			set
			{
				servicePref previousValue = this._servicePref.Entity;
				if (((previousValue != value) 
							|| (this._servicePref.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._servicePref.Entity = null;
						previousValue.member.Remove(this);
					}
					this._servicePref.Entity = value;
					if ((value != null))
					{
						value.member.Add(this);
						this._servicePrefFK = value.servicePrefID;
					}
					else
					{
						this._servicePrefFK = default(Nullable<int>);
					}
					this.SendPropertyChanged("servicePref");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dailyPref_member", Storage="_dailyPref", ThisKey="dailyPrefFK", OtherKey="dailyPrefID", IsForeignKey=true)]
		public dailyPref dailyPref
		{
			get
			{
				return this._dailyPref.Entity;
			}
			set
			{
				dailyPref previousValue = this._dailyPref.Entity;
				if (((previousValue != value) 
							|| (this._dailyPref.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dailyPref.Entity = null;
						previousValue.member.Remove(this);
					}
					this._dailyPref.Entity = value;
					if ((value != null))
					{
						value.member.Add(this);
						this._dailyPrefFK = value.dailyPrefID;
					}
					else
					{
						this._dailyPrefFK = default(Nullable<int>);
					}
					this.SendPropertyChanged("dailyPref");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dailyPref")]
	public partial class dailyPref : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dailyPrefID;
		
		private System.DateTime _dailyPrefStartDate;
		
		private System.Nullable<System.DateTime> _dailyPrefEndDate;
		
		private int _dayFK;
		
		private EntitySet<member> _member;
		
		private EntityRef<days> _days;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndailyPrefIDChanging(int value);
    partial void OndailyPrefIDChanged();
    partial void OndailyPrefStartDateChanging(System.DateTime value);
    partial void OndailyPrefStartDateChanged();
    partial void OndailyPrefEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OndailyPrefEndDateChanged();
    partial void OndayFKChanging(int value);
    partial void OndayFKChanged();
    #endregion
		
		public dailyPref()
		{
			this._member = new EntitySet<member>(new Action<member>(this.attach_member), new Action<member>(this.detach_member));
			this._days = default(EntityRef<days>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dailyPrefID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dailyPrefID
		{
			get
			{
				return this._dailyPrefID;
			}
			set
			{
				if ((this._dailyPrefID != value))
				{
					this.OndailyPrefIDChanging(value);
					this.SendPropertyChanging();
					this._dailyPrefID = value;
					this.SendPropertyChanged("dailyPrefID");
					this.OndailyPrefIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dailyPrefStartDate", DbType="DateTime2 NOT NULL")]
		public System.DateTime dailyPrefStartDate
		{
			get
			{
				return this._dailyPrefStartDate;
			}
			set
			{
				if ((this._dailyPrefStartDate != value))
				{
					this.OndailyPrefStartDateChanging(value);
					this.SendPropertyChanging();
					this._dailyPrefStartDate = value;
					this.SendPropertyChanged("dailyPrefStartDate");
					this.OndailyPrefStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dailyPrefEndDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> dailyPrefEndDate
		{
			get
			{
				return this._dailyPrefEndDate;
			}
			set
			{
				if ((this._dailyPrefEndDate != value))
				{
					this.OndailyPrefEndDateChanging(value);
					this.SendPropertyChanging();
					this._dailyPrefEndDate = value;
					this.SendPropertyChanged("dailyPrefEndDate");
					this.OndailyPrefEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dayFK", DbType="Int NOT NULL")]
		public int dayFK
		{
			get
			{
				return this._dayFK;
			}
			set
			{
				if ((this._dayFK != value))
				{
					if (this._days.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndayFKChanging(value);
					this.SendPropertyChanging();
					this._dayFK = value;
					this.SendPropertyChanged("dayFK");
					this.OndayFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dailyPref_member", Storage="_member", ThisKey="dailyPrefID", OtherKey="dailyPrefFK")]
		public EntitySet<member> member
		{
			get
			{
				return this._member;
			}
			set
			{
				this._member.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="days_dailyPref", Storage="_days", ThisKey="dayFK", OtherKey="dayID", IsForeignKey=true)]
		public days days
		{
			get
			{
				return this._days.Entity;
			}
			set
			{
				days previousValue = this._days.Entity;
				if (((previousValue != value) 
							|| (this._days.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._days.Entity = null;
						previousValue.dailyPref.Remove(this);
					}
					this._days.Entity = value;
					if ((value != null))
					{
						value.dailyPref.Add(this);
						this._dayFK = value.dayID;
					}
					else
					{
						this._dayFK = default(int);
					}
					this.SendPropertyChanged("days");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_member(member entity)
		{
			this.SendPropertyChanging();
			entity.dailyPref = this;
		}
		
		private void detach_member(member entity)
		{
			this.SendPropertyChanging();
			entity.dailyPref = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.days")]
	public partial class days : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dayID;
		
		private string _dayName;
		
		private EntitySet<dailyPref> _dailyPref;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndayIDChanging(int value);
    partial void OndayIDChanged();
    partial void OndayNameChanging(string value);
    partial void OndayNameChanged();
    #endregion
		
		public days()
		{
			this._dailyPref = new EntitySet<dailyPref>(new Action<dailyPref>(this.attach_dailyPref), new Action<dailyPref>(this.detach_dailyPref));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dayID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dayID
		{
			get
			{
				return this._dayID;
			}
			set
			{
				if ((this._dayID != value))
				{
					this.OndayIDChanging(value);
					this.SendPropertyChanging();
					this._dayID = value;
					this.SendPropertyChanged("dayID");
					this.OndayIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dayName", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string dayName
		{
			get
			{
				return this._dayName;
			}
			set
			{
				if ((this._dayName != value))
				{
					this.OndayNameChanging(value);
					this.SendPropertyChanging();
					this._dayName = value;
					this.SendPropertyChanged("dayName");
					this.OndayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="days_dailyPref", Storage="_dailyPref", ThisKey="dayID", OtherKey="dayFK")]
		public EntitySet<dailyPref> dailyPref
		{
			get
			{
				return this._dailyPref;
			}
			set
			{
				this._dailyPref.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dailyPref(dailyPref entity)
		{
			this.SendPropertyChanging();
			entity.days = this;
		}
		
		private void detach_dailyPref(dailyPref entity)
		{
			this.SendPropertyChanging();
			entity.days = null;
		}
	}
}
#pragma warning restore 1591
