<?xml version="1.0" encoding="utf-8"?><Database Name="bddPandami" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=FORM227\SQLEXPRESS;Initial Catalog=bddPandami;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="bddPandamiConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.servicePref" Member="servicePref">
    <Type Name="servicePref">
      <Column Name="servicePrefID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="choiceStartDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="choiceEndDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="serviceNameFK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="servicePref_member" Member="member" ThisKey="servicePrefID" OtherKey="servicePrefFK" Type="member" />
      <Association Name="serviceName_servicePref" Member="serviceName" ThisKey="serviceNameFK" OtherKey="serviceID" Type="serviceName" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.serviceName" Member="serviceName">
    <Type Name="serviceName">
      <Column Name="serviceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="serviceName" Member="serviceName1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="serviceCategoryFK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="serviceName_servicePref" Member="servicePref" ThisKey="serviceID" OtherKey="serviceNameFK" Type="servicePref" />
    </Type>
  </Table>
  <Table Name="dbo.member" Member="member">
    <Type Name="member">
      <Column Name="memberID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="birthdate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cityFK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="serviceRequestFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dailyPrefFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="servicePrefFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="servicePref_member" Member="servicePref" ThisKey="servicePrefFK" OtherKey="servicePrefID" Type="servicePref" IsForeignKey="true" />
      <Association Name="dailyPref_member" Member="dailyPref" ThisKey="dailyPrefFK" OtherKey="dailyPrefID" Type="dailyPref" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.dailyPref" Member="dailyPref">
    <Type Name="dailyPref">
      <Column Name="dailyPrefID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dailyPrefStartDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="dailyPrefEndDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="dayFK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="dailyPref_member" Member="member" ThisKey="dailyPrefID" OtherKey="dailyPrefFK" Type="member" />
      <Association Name="days_dailyPref" Member="days" ThisKey="dayFK" OtherKey="dayID" Type="days" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.days" Member="days">
    <Type Name="days">
      <Column Name="dayID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dayName" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="days_dailyPref" Member="dailyPref" ThisKey="dayID" OtherKey="dayFK" Type="dailyPref" />
    </Type>
  </Table>
</Database>