<?xml version="1.0" encoding="utf-8"?><Database Name="bddPandami" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=FORM227\SQLEXPRESS;Initial Catalog=bddPandami;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="bddPandamiConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.serviceRequest" Member="serviceRequest">
    <Type Name="serviceRequest">
      <Column Name="serviceRequestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="serviceStartDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="serviceEndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="serviceAddress" Type="System.String" DbType="NVarChar(120)" CanBeNull="true" />
      <Column Name="priority" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="creationDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="cancelDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="startTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="serviceFK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="serviceCityFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="memberFK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="voluntaryMemberFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="serviceRequest_requestAnswer" Member="requestAnswer" ThisKey="serviceRequestID" OtherKey="serviceRFK" Type="requestAnswer" />
      <Association Name="member_serviceRequest" Member="member" ThisKey="memberFK" OtherKey="memberID" Type="member" IsForeignKey="true" />
      <Association Name="member_serviceRequest1" Member="member1" ThisKey="voluntaryMemberFK" OtherKey="memberID" Type="member" IsForeignKey="true" />
      <Association Name="serviceName_serviceRequest" Member="serviceName" ThisKey="serviceFK" OtherKey="serviceID" Type="serviceName" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.member" Member="member">
    <Type Name="member">
      <Column Name="memberID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="birthdate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cityFK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="serviceRequestFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dailyPrefFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="servicePrefFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="member_serviceRequest" Member="serviceRequest" ThisKey="memberID" OtherKey="memberFK" Type="serviceRequest" />
      <Association Name="member_serviceRequest1" Member="serviceRequest1" ThisKey="memberID" OtherKey="voluntaryMemberFK" Type="serviceRequest" />
    </Type>
  </Table>
  <Table Name="dbo.serviceName" Member="serviceName">
    <Type Name="serviceName">
      <Column Name="serviceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="serviceName" Member="serviceName1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="serviceCategoryFK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="serviceName_serviceRequest" Member="serviceRequest" ThisKey="serviceID" OtherKey="serviceFK" Type="serviceRequest" />
    </Type>
  </Table>
  <Table Name="dbo.requestAnswer" Member="requestAnswer">
    <Type Name="requestAnswer">
      <Column Name="refusalDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="acceptanceDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="cancelDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="answerDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="serviceRFK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="answerFK" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="serviceRequest_requestAnswer" Member="serviceRequest" ThisKey="serviceRFK" OtherKey="serviceRequestID" Type="serviceRequest" IsForeignKey="true" />
      <Association Name="answer_requestAnswer" Member="answer" ThisKey="answerFK" OtherKey="answerID" Type="answer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.answer" Member="answer">
    <Type Name="answer">
      <Column Name="answerID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="answer" Member="answer1" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Association Name="answer_requestAnswer" Member="requestAnswer" ThisKey="answerID" OtherKey="answerFK" Type="requestAnswer" />
    </Type>
  </Table>
</Database>